### ISSUE TITLE
Cruise Power chart

### ISSUE THREAD

**Issue by squankum** [beauzo/kneeboard#1]
Hi Beauzo,

Good take on an all-in-one checklist.

Also interested in the speed/fuel Cruise graph, I prefer it over the chart in the POH.  I assume you built it, how did you do that?
   
![CruiseGraph](https://github.com/beauzo/kneeboard/assets/14014601/161ca275-9884-49dd-a696-7604a143b369)

**Comment by squankum** [comment]
Disregard, I figured it out.
![C172G CruiseGraph 2023 07 23](https://github.com/beauzo/kneeboard/assets/14014601/b44b92d2-7c73-4508-8312-fb0e592878b0)

**Comment by beauzo** [comment]
Hello, sorry for the late response. Looks like you figured it out. It's been awhile, but if I remember correctly, I made the plots in Tableau. The data is, of course, sourced from the POH.

Looks like you have a more efficient airplane... ;)
